project_type: maven
release_branch: develop-cloudempiere
linear_project: CLD
version_files:
  - path: com.cloudempiere.searchindex.parent/pom.xml
    pattern: '<version>(.*?)</version>'
    line_range: [1, 20]
  - path: com.cloudempiere.searchindex/META-INF/MANIFEST.MF
    pattern: 'Bundle-Version: (.*?)\.qualifier'
  - path: com.cloudempiere.searchindex.ui/META-INF/MANIFEST.MF
    pattern: 'Bundle-Version: (.*?)\.qualifier'
  - path: com.cloudempiere.searchindex.test/META-INF/MANIFEST.MF
    pattern: 'Bundle-Version: (.*?)\.qualifier'
build_command: mvn clean compile -DskipTests
files_to_update:
  - CHANGELOG.md
  - FEATURES.md
